version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/funeral-backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "main"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "java"

  - package-ecosystem: "npm"
    directory: "/funeral-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "main"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "main"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/docker_bak"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    target-branch: "main"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"
