#!/bin/bash
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         ⚠️  IMPORTANT: Backend Restart Required ⚠️            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "You MUST restart the backend for changes to take effect!"
echo ""
echo "In Terminal #1, run:"
echo "  cd funeral-backend"
echo "  mvn clean compile quarkus:dev"
echo ""
echo "Then in Terminal #2, run:"
echo "  cd funeral && ./deploy_fix_and_test.sh"
echo ""
