package io.oci.resource;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.hasSize;

@QuarkusTest
public class MirrorResourceTest {

    @Test
    public void testMirrorWithoutSourceImage() {
        given().contentType(
                ContentType.URLENC
        )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        400
                )
                .contentType(
                        ContentType.JSON
                )
                .body(
                        "errors",
                        hasSize(
                                greaterThanOrEqualTo(
                                        1
                                )
                        )
                )
                .body(
                        "errors[0].message",
                        containsString(
                                "Source image is required"
                        )
                );
    }

    @Test
    public void testMirrorWithEmptySourceImage() {
        given().contentType(
                ContentType.URLENC
        )
                .formParam(
                        "sourceImage",
                        ""
                )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        400
                )
                .contentType(
                        ContentType.JSON
                )
                .body(
                        "errors",
                        hasSize(
                                greaterThanOrEqualTo(
                                        1
                                )
                        )
                )
                .body(
                        "errors[0].message",
                        containsString(
                                "Source image is required"
                        )
                );
    }

    @Test
    public void testMirrorValidation() {
        given().contentType(
                ContentType.URLENC
        )
                .formParam(
                        "sourceImage",
                        "nginx:latest"
                )
                .formParam(
                        "targetRepository",
                        "my-nginx"
                )
                .formParam(
                        "targetTag",
                        "v1.0"
                )
                .formParam(
                        "protocol",
                        "https"
                )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        anyOf(
                                is(
                                        200
                                ),
                                is(
                                        202
                                ),
                                is(
                                        201
                                ),
                                is(
                                        500
                                ),
                                is(
                                        503
                                )
                        )
                )
                .contentType(
                        ContentType.JSON
                );
    }

    @Test
    public void testMirrorWithAuth() {
        given().contentType(
                ContentType.URLENC
        )
                .formParam(
                        "sourceImage",
                        "ubuntu:20.04"
                )
                .formParam(
                        "protocol",
                        "https"
                )
                .formParam(
                        "username",
                        "testuser"
                )
                .formParam(
                        "password",
                        "testpass"
                )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        anyOf(
                                is(
                                        200
                                ),
                                is(
                                        202
                                ),
                                is(
                                        201
                                ),
                                is(
                                        401
                                ),
                                is(
                                        403
                                ),
                                is(
                                        500
                                )
                        )
                )
                .contentType(
                        ContentType.JSON
                );
    }

    @Test
    public void testMirrorWithHTTPProtocol() {
        given().contentType(
                ContentType.URLENC
        )
                .formParam(
                        "sourceImage",
                        "nginx:latest"
                )
                .formParam(
                        "protocol",
                        "http"
                )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        anyOf(
                                is(
                                        200
                                ),
                                is(
                                        202
                                ),
                                is(
                                        201
                                ),
                                is(
                                        500
                                ),
                                is(
                                        503
                                )
                        )
                )
                .contentType(
                        ContentType.JSON
                );
    }

    @Test
    public void testMirrorWithInvalidProtocol() {
        given().contentType(
                ContentType.URLENC
        )
                .formParam(
                        "sourceImage",
                        "nginx:latest"
                )
                .formParam(
                        "protocol",
                        "ftp"
                )
                .when()
                .post(
                        "/funeral_addition/mirror/pull"
                )
                .then()
                .statusCode(
                        anyOf(
                                is(
                                        200
                                ),
                                is(
                                        202
                                ),
                                is(
                                        201
                                ),
                                is(
                                        500
                                ),
                                is(
                                        503
                                )
                        )
                )
                .contentType(
                        ContentType.JSON
                );
    }
}
